name: Deploy Github Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Deploy Github Pages
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2 # Uses version from package.json#packageManager
      - name: Setup Node (using .node-version)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Action
      - name: Build Github Pages
        run: pnpm build "src/index.html"
      - name: Deploy Github Pages to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
